# Base URL
@BookStore.Api_HostAddress = https://localhost:5076

### Get All Books
GET {{BookStore.Api_HostAddress}}/api/Books
Accept: application/json

### Get Book By ID
GET {{BookStore.Api_HostAddress}}/api/Books/{ede91627-1f20-42d9-bff6-f34134166b8c}
Accept: application/json

### Create a New Book
POST {{BookStore.Api_HostAddress}}/api/Books
Content-Type: application/json

{
  "title": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "isbn": "9780743273565",
  "publishedDate": "1925-04-10T00:00:00"
}

### Update an Existing Book
PUT {{BookStore.Api_HostAddress}}/api/Books/{ede91627-1f20-42d9-bff6-f34134166b8c}
Content-Type: application/json

{
  "bookId": "{ede91627-1f20-42d9-bff6-f34134166b8c}",
  "title": "The Great Gatsby (Updated)",
  "author": "F. Scott Fitzgerald",
  "isbn": "9780743273455",
  "publishedDate": "1925-04-10T00:00:00"
}

### Delete a Book
DELETE {{BookStore.Api_HostAddress}}/api/books/{ede91627-1f20-42d9-bff6-f34134166b8c}
